---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my deployment
  labels:
    app: new1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: new1
  template:
    metadata:
      labels:
        app: new1
    spec:
      containers:
        - name: sample deployment
          image: gcr.io/vyshnavi1-374012/firstimage:1
          port:
            - containerPort: 8080
              protocol: TCP
...
  
