---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx-1"
  namespace: "default"
  labels:
    app: "nginx-1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "nginx-1"
  template:
    metadata:
      labels:
        app: "nginx-1"
    spec:
      containers:
      - name: "sasuke-sha256-1"
        image: "gcr.io/bestrealtimeprojects/sasuke@sha256:d1b2ca515c4e3b8f1321ac969aea1d4a446acdd8c132faf2f9e1515d4e908671"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "nginx-1-hpa-qeof"
  namespace: "default"
  labels:
    app: "nginx-1"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "nginx-1"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80

...

---
apiVersion: v1
kind: Service
metadata:
  name: service-for-deployment
  labels:
    app: "nginx-1"
spec:
  type: LoadBalancer
  selector:
    app: "nginx-1"
  ports:
    - port: 8050
      targetPort: 8080
...
  
