---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: new1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: new1
  template:
    metadata:
      labels:
        app: new1
    spec:
      containers:
        - name: sample-deployment
          image: gcr.io/bestrealtimeprojects/sasuke:v1
          ports:
            - containerPort: 8080
              protocol: TCP
...

---
apiVersion: v1
kind: Service
metadata:
  name: service-for-deployment
  labels:
    app: new1
spec:
  type: LoadBalancer
  selector:
    app: new1
  ports:
    - port: 8050
      targetPort: 8080
...
  
